const lightPalette = {
  teal: '#1FA6A6',
  aqua: '#67D6D1',
  sky: '#7CB8FF',
  peach: '#FF8E72',
  gold: '#F4B860',
  lilac: '#A88CFF',
  blush: '#FFD9CF',
  mint: '#D8F5EE',
  ice: '#E8F4FF',
  sun: '#FFF1C7',
  ink: '#18222B',
  slate: '#5B6874',
  mist: '#94A0A9',
  line: '#DCE5EB',
  canvas: '#F6FBFF',
  white: '#FFFFFF'
} as const;

const darkPalette = {
  teal: '#56D9D2',
  aqua: '#2D7F84',
  sky: '#6FAAFF',
  peach: '#FF9E80',
  gold: '#F5C46E',
  lilac: '#B09BFF',
  blush: '#442A30',
  mint: '#18352F',
  ice: '#182838',
  sun: '#3A3220',
  ink: '#F2F7FB',
  slate: '#B8C3CC',
  mist: '#82919E',
  line: '#243543',
  canvas: '#0B1218',
  white: '#FFFFFF'
} as const;

export const lightColors = {
  primary: lightPalette.teal,
  secondary: lightPalette.sky,
  tertiary: lightPalette.lilac,
  success: lightPalette.teal,
  warning: lightPalette.gold,
  danger: lightPalette.peach,
  info: lightPalette.sky,
  background: lightPalette.canvas,
  backgroundAccent: '#EEF8FC',
  backgroundCanvas: '#F8FCFF',
  surface: 'rgba(255,255,255,0.88)',
  surfaceElevated: lightPalette.white,
  surfaceSecondary: '#F1F9FF',
  surfaceMuted: '#EDF8F5',
  surfaceInverse: '#162028',
  card: lightPalette.white,
  border: lightPalette.line,
  divider: '#E8EFF4',
  overlay: 'rgba(24, 34, 43, 0.12)',
  overlayStrong: 'rgba(10, 22, 30, 0.48)',
  textPrimary: lightPalette.ink,
  textSecondary: lightPalette.slate,
  textMuted: lightPalette.mist,
  textOnPrimary: lightPalette.white,
  textOnAccent: lightPalette.ink,
  tabBar: 'rgba(255,255,255,0.94)',
  heroStart: lightPalette.aqua,
  heroEnd: lightPalette.sky,
  heroAccent: lightPalette.lilac,
  heroGlow: '#FFE7D9',
  chip: '#EEF8FB',
  chipActive: '#D8F4F4',
  meditationTint: '#DFF8F3',
  sleepTint: '#E6EEFF',
  breathingTint: '#F3FADE',
  courseTint: '#FFF1E2',
  icon: lightPalette.ink,
  iconMuted: lightPalette.mist,
  text: lightPalette.ink,
  onPrimary: lightPalette.white,
  onSecondary: lightPalette.white,
  white: lightPalette.white
} as const;

export const darkColors = {
  primary: darkPalette.teal,
  secondary: darkPalette.sky,
  tertiary: darkPalette.lilac,
  success: darkPalette.teal,
  warning: darkPalette.gold,
  danger: darkPalette.peach,
  info: darkPalette.sky,
  background: darkPalette.canvas,
  backgroundAccent: '#0F1820',
  backgroundCanvas: '#0A1117',
  surface: 'rgba(21, 29, 38, 0.9)',
  surfaceElevated: '#151E26',
  surfaceSecondary: '#162430',
  surfaceMuted: '#122028',
  surfaceInverse: '#F2F7FB',
  card: '#151E26',
  border: darkPalette.line,
  divider: '#1D2A35',
  overlay: 'rgba(0, 0, 0, 0.34)',
  overlayStrong: 'rgba(0, 0, 0, 0.6)',
  textPrimary: darkPalette.ink,
  textSecondary: darkPalette.slate,
  textMuted: darkPalette.mist,
  textOnPrimary: '#081013',
  textOnAccent: darkPalette.ink,
  tabBar: 'rgba(19, 27, 35, 0.96)',
  heroStart: '#123D46',
  heroEnd: '#1A3152',
  heroAccent: '#32284E',
  heroGlow: '#3A241E',
  chip: '#15242C',
  chipActive: '#1A4747',
  meditationTint: '#16312D',
  sleepTint: '#18253A',
  breathingTint: '#24311D',
  courseTint: '#31261F',
  icon: darkPalette.ink,
  iconMuted: darkPalette.mist,
  text: darkPalette.ink,
  onPrimary: '#081013',
  onSecondary: '#081013',
  white: darkPalette.white
} as const;
